spring:
  application:
    name: EurekaServer
  security:
    basic:
      enabled: true
    user:
      name: eureka-microservices-admin
      password: akeruesecivresorcimnimda

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
